steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ["install"]
- name: 'gcr.io/cloud-builders/npm'
  args: ["run", "build"]
  dir: 'dist'
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "coloriq:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', "coloriq:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/my-deployment'
  - 'my-container=coloriq:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=color-iq-dev'
