kind: Ingress
metadata:
  name: coloriq
spec:
  rules:
  - http:
      paths:
      - path: /game/*
        backend:
          serviceName: coloriq
          servicePort: 80
kind: Service
apiVersion: v1
metadata:
  name: coloriq
spec:
  selector:
     run: coloriq
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer