apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coloriq-ingress
spec:
  rules:
  - http:
      paths:
      - path: /game/*
        backend:
          serviceName: coloriq
          servicePort: 80
apiVersion: v1
kind: Service
metadata:
  name: coloriq-service
spec:
  selector:
    app: coloriq
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80